### ISSUE TITLE
compilation linux

### ISSUE THREAD

**Issue by Chr0nos** [alelievr/shaderRender#1]
j ai un petit soucis avec la compilation sous linux:

> ➜  shaderRender git:(master) make   
> \033[38;5;119m➤ Object: obj/main.o\033[38;5;113m\nclang -Werror -ferror-limit=999 -funroll-loops -O2 -Iglfw/include -Iinc -ISOIL2-clone/incs -Ifmod/inc -o obj/main.o -c src/main.c\033[0m
> src/main.c:23:10: fatal error: 'OpenGL/glext.h' file not found
> #include <OpenGL/glext.h>
>          ^
> 1 error generated.
> make: *** [Makefile:202: obj/main.o] Error 1

➜  shaderRender git:(master) find /usr/include -name glext.h        
/usr/include/gtkglext-1.0/gdk/glext/glext.h
/usr/include/GL/glext.h
/usr/include/GLES/glext.h

apparement glext.h ne se trouve pas dans le dossier OpenGL mais dans GL sous linux

**Comment by Chr0nos** [comment]
en attendant j ai fait un : sudo ln -s /usr/include/GL /usr/include/OpenGL

il reste un:
> src/shader.c:83:3: error: implicitly declaring library function 'strlcpy' with type 'unsigned long (char *, >const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
>                strlcpy(dst, ptr, nl - ptr + 1);

**Comment by alelievr** [comment]
C'est ok pour la compilation sous linux, c'était juste une diff de path opengl entre mac et linux, pour le strlcpy j'ai rajouter a la compile la lib bsd du coup si tu l'as pas encore installe le packet `libsdb-dev`

**Comment by Chr0nos** [comment]
il reste une petite erreur:

src/wav.c:63:15: error: implicit conversion from 'int' to 'char' changes value
      from 255 to -1 [-Werror,-Wconstant-conversion]
                buff[j++] = 255;

**Comment by alelievr** [comment]
ok, normalement c'est fix sur la derniere version, c'est bizare sur mon linux ca compilait sans probleme avec clang et gcc
